"use client";

import { Frame, PageTitle } from "../components/frame";

const rows = [["TF-IDF + Logistic Regression", "Flood classification", "F1 · 0.67", "12 ms", "Baseline"], ["Hybrid NER + Gazetteer", "Entity extraction", "Coverage · 0.89", "18 ms", "Active"], ["Isolation Forest", "River anomaly", "Recall · 0.91", "8 ms", "Active"], ["ARIMA / XGBoost", "Short-horizon forecast", "RMSE · 0.42", "24 ms", "Candidate"]];

function download(name: string, content: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }

export default function ModelsPage() {
  function exportMetrics() { download("aegis-model-evaluation.json", JSON.stringify({ dataset: "phase3-flood-fixture-v1", models: rows, policy: "risk-v1" }, null, 2), "application/json"); }
  function openReport() { download("aegis-model-evaluation-report.md", "# AEGIS Model Evaluation\n\nDataset: phase3-flood-fixture-v1\n\n- NLP macro F1: 0.67\n- Retrieval Recall@5: 1.00\n- Anomaly ensemble validation: 0.89\n- Active risk policy: risk-v1\n", "text/markdown"); }
  return <Frame active="Model evaluation"><section className="metrics"><div className="metric"><p>NLP macro F1</p><strong className="amber">0.67</strong><small>baseline · held-out fixture</small></div><div className="metric"><p>Retrieval Recall@5</p><strong className="green">1.00</strong><small>labelled acceptance set</small></div><div className="metric"><p>Anomaly ensemble</p><strong>0.89</strong><small>validation score</small></div><div className="metric"><p>Active policy</p><strong>v1</strong><small>risk-v1 · deterministic</small></div></section><section className="panel"><div className="card-heading"><PageTitle eyebrow="MODEL REGISTRY" title="Evaluation comparison" action="" /><button className="button small" onClick={exportMetrics}>Export metrics ↓</button></div><div className="table-head"><span>Model</span><span>Task</span><span>Metric</span><span>Latency</span><span>Status</span></div>{rows.map(row => <div className="table-row model-row" key={row[0]}><div><strong>{row[0]}</strong></div><span>{row[1]}</span><span>{row[2]}</span><span>{row[3]}</span><span className="model-status">{row[4]}</span></div>)}</section><section className="bottom-grid"><div className="panel"><PageTitle eyebrow="REPRODUCIBILITY" title="Evaluation artifacts" /><p className="muted">Every active model records its dataset version, metrics, inference latency, and activation history.</p><button className="button primary small" onClick={openReport}>Open evaluation report</button></div><div className="panel"><PageTitle eyebrow="RISK GOVERNANCE" title="Policy version" /><div className="big-stat">risk-v1 <small>6 weighted components · threshold tested</small></div></div></section></Frame>;
}
