"use client";

import { useState } from "react";
import { Frame, PageTitle } from "../components/frame";

type NodeType = "incident" | "event" | "infra";
type GraphNode = { id: string; label: string; type: NodeType; x: number; y: number; detail: string };
const nodes: GraphNode[] = [
  { id: "incident", label: "Flood incident", type: "incident", x: 500, y: 235, detail: "INC-042 · CRITICAL · risk 0.82" },
  { id: "river", label: "River spike", type: "event", x: 220, y: 105, detail: "Melamchi · 7.8 m" },
  { id: "road", label: "Road closure", type: "event", x: 780, y: 105, detail: "Araniko Highway" },
  { id: "highway", label: "Araniko Highway", type: "infra", x: 205, y: 365, detail: "Transport dependency" },
  { id: "hospital", label: "Melamchi Hospital", type: "infra", x: 795, y: 365, detail: "Emergency dependency" },
];
const edges = [{ from: "river", to: "incident", label: "CAUSES" }, { from: "road", to: "incident", label: "REPORTS" }, { from: "incident", to: "highway", label: "AFFECTS" }, { from: "incident", to: "hospital", label: "AFFECTS" }];

export default function GraphPage() {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState("incident"); const [paths, setPaths] = useState(edges.map(edge => `${nodes.find(node => node.id === edge.from)?.label} → ${nodes.find(node => node.id === edge.to)?.label}`)); const [message, setMessage] = useState("4 connected paths · BFS depth 3");
  function traverse() { const value = query.trim().toLowerCase(); const matches = edges.filter(edge => { const from = nodes.find(node => node.id === edge.from); const to = nodes.find(node => node.id === edge.to); return !value || `${from?.label} ${to?.label} ${edge.label}`.toLowerCase().includes(value); }); setPaths(matches.map(edge => `${nodes.find(node => node.id === edge.from)?.label} → ${nodes.find(node => node.id === edge.to)?.label}`)); setMessage(`${matches.length} connected path${matches.length === 1 ? "" : "s"} · query: ${value || "active incident"}`); }
  function reset() { setQuery(""); setSelected("incident"); setPaths(edges.map(edge => `${nodes.find(node => node.id === edge.from)?.label} → ${nodes.find(node => node.id === edge.to)?.label}`)); setMessage("4 connected paths · BFS depth 3"); }
  return <Frame active="Knowledge graph"><section className="panel"><div className="card-heading"><PageTitle eyebrow="NEO4J IMPACT GRAPH · BFS DEPTH 3" title="Infrastructure dependency graph" action="" /><button className="button small" onClick={reset}>Reset view</button></div><div className="graph-actions"><span className="graph-status">● LIVE GRAPH PROJECTION · {selected.toUpperCase()}</span></div><div className="graph-canvas graph-svg-wrap"><svg viewBox="0 0 1000 470" role="img" aria-label="AEGIS incident infrastructure dependency graph"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#63b8a5" /></marker></defs>{edges.map(edge => { const from = nodes.find(node => node.id === edge.from)!; const to = nodes.find(node => node.id === edge.to)!; return <g key={`${edge.from}-${edge.to}`} className={selected === edge.from || selected === edge.to ? "graph-link active" : "graph-link"}><line x1={from.x} y1={from.y} x2={to.x} y2={to.y} markerEnd="url(#arrow)" /><text x={(from.x + to.x) / 2} y={(from.y + to.y) / 2 - 9}>{edge.label}</text></g>; })}{nodes.map(node => <g className={`graph-svg-node ${node.type} ${selected === node.id ? "selected" : ""}`} key={node.id} onClick={() => setSelected(node.id)}><circle cx={node.x} cy={node.y} r="26" /><text className="node-label" x={node.x} y={node.y + 48}>{node.label}</text><text className="node-detail" x={node.x} y={node.y + 64}>{node.detail}</text></g>)}</svg><div className="graph-legend"><span><i className="node-dot incident" />Incident</span><span><i className="node-dot event" />Event</span><span><i className="node-dot infra" />Infrastructure</span></div></div></section><section className="bottom-grid"><div className="panel"><PageTitle eyebrow="TRAVERSAL" title="Impact paths" /><p className="notice">{message}</p>{paths.map(path => <div className="path-row" key={path}>{path}</div>)}</div><div className="panel"><PageTitle eyebrow="GRAPH QUERY" title="Explore dependencies" /><input className="search" value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === "Enter" && traverse()} placeholder="Search district, river, road..." /><button className="button primary small" onClick={traverse}>Run traversal</button></div></section></Frame>;
}
