"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Frame } from "../components/frame";
import { apiRequest } from "../lib/api";

type Incident = { id: string; title: string; district: string; type: string; level: string; score: string; updated: string };
const seed: Incident[] = [
  { id: "INC-042", title: "Sindhupalchok flood risk", district: "Sindhupalchok", type: "FLOOD INCIDENT", level: "CRITICAL", score: "0.82", updated: "12 min ago" },
  { id: "INC-041", title: "Melamchi river threshold breach", district: "Sindhupalchok", type: "HYDROLOGY", level: "HIGH", score: "0.67", updated: "38 min ago" },
  { id: "INC-039", title: "Araniko Highway disruption", district: "Dolakha", type: "INFRASTRUCTURE", level: "MODERATE", score: "0.44", updated: "1 hr ago" },
];

export default function IncidentsPage() {
  const [live, setLive] = useState(seed); const [filter, setFilter] = useState("ALL"); const [query, setQuery] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { apiRequest("/api/v1/incidents").then(r => r.ok ? r.json() : null).then(payload => { if (payload?.incidents?.length) setLive(payload.incidents.map((item: Record<string, unknown>) => ({ id: String(item.incident_id), title: `${String(item.district || "District")} flood incident`, district: String(item.district || "Unknown"), type: "FLOOD INCIDENT", level: String((item.risk as Record<string, unknown>)?.level || "OPEN"), score: String((item.risk as Record<string, unknown>)?.risk || "—"), updated: "just now" }))); }).catch(() => setMessage("Live incident API unavailable — showing the evaluation fixture.")); }, []);
  const visible = useMemo(() => live.filter(item => (filter === "ALL" || item.level === filter) && `${item.title} ${item.id} ${item.district}`.toLowerCase().includes(query.toLowerCase())), [live, filter, query]);
  function exportReport() { const csv = ["id,title,district,type,level,score,updated", ...visible.map(item => [item.id, item.title, item.district, item.type, item.level, item.score, item.updated].map(value => `"${value.replaceAll('"', '""')}"`).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = "aegis-incidents.csv"; link.click(); URL.revokeObjectURL(url); setMessage(`Exported ${visible.length} incident${visible.length === 1 ? "" : "s"}.`); }
  return <Frame active="Incidents"><section className="panel"><div className="card-heading"><div><p className="eyebrow">PRIORITIZED QUEUE · {live.length} ACTIVE</p><h2>Incident intelligence</h2></div><button className="button small" onClick={exportReport}>Export report ↓</button></div><div className="filter-row">{["ALL", "CRITICAL", "HIGH", "ACKNOWLEDGED"].map(value => <button className={`filter ${filter === value ? "active" : ""}`} onClick={() => setFilter(value)} key={value}>{value[0] + value.slice(1).toLowerCase()} <b>{value === "ALL" ? live.length : live.filter(item => item.level === value).length}</b></button>)}<input className="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search incidents..." /></div>{message && <p className="notice">{message}</p>}<div className="table-head"><span>Incident</span><span>District</span><span>Type</span><span>Risk</span><span>Updated</span></div>{visible.map(item => <Link className="table-row" href={`/incidents/${item.id}`} key={item.id}><div><strong>{item.title}</strong><small>{item.id}</small></div><span>{item.district}</span><span>{item.type}</span><span><i className={`status-dot ${item.level.toLowerCase()}`} />{item.level}<small className="score-inline">{item.score}</small></span><span>{item.updated} <b className="row-arrow">→</b></span></Link>)}{!visible.length && <p className="empty-state">No incidents match this filter.</p>}</section><section className="bottom-grid"><div className="panel"><div className="card-heading"><div><p className="eyebrow">INCIDENT LIFECYCLE</p><h2>Workflow status</h2></div></div><div className="workflow"><b>12</b><span>Open</span><b>06</b><span>Acknowledged</span><b>03</b><span>Investigating</span><b>01</b><span>Resolved</span></div></div><div className="panel"><p className="eyebrow">DETECTION QUALITY</p><h2>Signal confidence</h2><div className="big-stat">94.2% <small>average source confidence</small></div><div className="progress-line"><span style={{ width: "94%" }} /></div></div></section></Frame>;
}
