"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Frame, PageTitle } from "../../components/frame";

type Incident = { incident_id: string; district?: string; event_types?: string[]; status?: string; risk?: { risk: number; level: string; components?: Record<string, number>; policy_version?: string }; notes?: { note: string; author: string }[] };
const fallback: Incident = { incident_id: "INC-042", district: "Sindhupalchok", event_types: ["HEAVY_RAIN", "FLOOD", "ROAD_CLOSURE"], status: "OPEN", risk: { risk: 0.82, level: "CRITICAL", components: { rainfall_anomaly: 0.91, river_anomaly: 0.87, forecast_probability: 0.79, infrastructure_impact: 0.75 }, policy_version: "risk-v1" }, notes: [] };

export default function IncidentDetail({ params }: { params: Promise<{ id: string }> }) {
  const [incidentId, setIncidentId] = useState("INC-042");
  const [incident, setIncident] = useState<Incident>(fallback);
  const [status, setStatus] = useState("OPEN");
  const [note, setNote] = useState("");
  useEffect(() => { params.then(({ id }) => { setIncidentId(id); fetch(`http://localhost:8000/api/v1/incidents/${id}`, { credentials: "include" }).then(r => r.ok ? r.json() : null).then(data => { if (data) { setIncident(data); setStatus(data.status || "OPEN"); } }).catch(() => undefined); }); }, [params]);
  const risk = incident.risk ?? fallback.risk!;
  const components = risk.components || {};
  const eventTypes = incident.event_types ?? fallback.event_types ?? [];
  async function changeStatus(value: string) { setStatus(value); const response = await fetch(`http://localhost:8000/api/v1/incidents/${incidentId}/status`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: value }) }); if (response.ok) setIncident(await response.json()); }
  async function addNote(event: React.FormEvent) { event.preventDefault(); if (!note.trim()) return; const response = await fetch(`http://localhost:8000/api/v1/incidents/${incidentId}/notes`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ note, author: "analyst" }) }); if (response.ok) { setIncident(await response.json()); setNote(""); } }
  return <Frame active="Incidents"><Link className="back-link" href="/incidents">← All incidents</Link><section className="detail-hero"><div><p className="eyebrow">{incidentId} · {status} INVESTIGATION</p><h2>{incident.district || "Flood incident"} flood risk</h2><p className="muted">Live incident record from the authenticated correlation service.</p></div><span className={`badge ${risk.level.toLowerCase()}`}>{risk.level} · {risk.risk.toFixed(2)}</span></section><section className="detail-grid"><div className="panel"><PageTitle eyebrow={`RISK BREAKDOWN · ${(risk.policy_version || "risk-v1").toUpperCase()}`} title="Transparent risk score" /><div className="risk-number">{risk.risk.toFixed(2)} <small>{risk.level}</small></div>{Object.entries(components).map(([key, value]) => <div className="bar-row" key={key}><span>{key.replaceAll("_", " ")}</span><b>{value.toFixed(2)}</b><i><em style={{width:`${value * 100}%`}} /></i></div>)}</div><div className="panel"><PageTitle eyebrow="INCIDENT TIMELINE" title="Signal correlation" /><div className="timeline">{eventTypes.map((event, index) => <Event time={`${9 + index}:00`} title={event.replaceAll("_", " ")} detail="Normalized event linked to incident" key={event} />)}<Event time="LIVE" title="Incident correlated" detail="Evidence and risk available" /></div></div></section><section className="panel"><PageTitle eyebrow="ANALYST ACTIONS" title="Investigation workspace" /><div className="action-grid"><Link className="action-card" href={`/evidence?incident=${incidentId}`}><strong>Review evidence</strong><span>Historical flood reports →</span></Link><Link className="action-card" href="/graph"><strong>Explore impact graph</strong><span>Infrastructure dependencies →</span></Link><label className="action-card"><strong>Update status</strong><select value={status} onChange={e => changeStatus(e.target.value)}><option>OPEN</option><option>ACKNOWLEDGED</option><option>INVESTIGATING</option><option>RESOLVED</option></select></label></div><form className="note-form" onSubmit={addNote}><input className="search" value={note} onChange={e => setNote(e.target.value)} placeholder="Add an analyst note" /><button className="button primary small">Save note</button></form>{incident.notes?.map((item, index) => <p className="muted" key={index}><b>{item.author}:</b> {item.note}</p>)}</section></Frame>;
}

function Event({time,title,detail}:{time:string;title:string;detail:string}) { return <div className="timeline-item"><time>{time}</time><span className="timeline-line" /><div><strong>{title}</strong><p>{detail}</p></div></div>; }
